modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/creep3rcrafter/Mystic-Potions/issues"
license = "All Rights Reserved"

[[mods]]
modId = "mysticpotions"
version = "${version}"
displayName = "Mystic Potions (Forge)"
displayURL = "https://github.com/creep3rcrafter/Mystic-Potions"
authors = "Creep3rCrafter"
description = '''
Adds New Potions To Minecraft!
'''
logoFile = "MysticPotions Logo HD720pC.png"

[[dependencies.mysticpotions]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticpotions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticpotions]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"