modLoader = "javafml"
loaderVersion = "[${forgeMajorVersion},)"
issueTrackerURL = "https://github.com/creep3rcrafter/Mystic-Potions/issues"
license = "All Rights Reserved"

[[mods]]
modId = "mysticpotions"
version = "${version}"
displayName = "Mystic Potions (Forge)"
displayURL = "https://github.com/creep3rcrafter/Mystic-Potions"
authors = "Creep3rCrafter"
description = '''
Adds New Potions To Minecraft!
'''
logoFile = "MysticPotions Logo HD720pC.png"

[[mixins]]
config = "mysticpotions-common.mixins.json"
[[mixins]]
config = "mysticpotions.mixins.json"

[[dependencies.mysticpotions]]
modId = "forge"
mandatory = true
versionRange = "[${forgeMajorVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticpotions]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticpotions]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "AFTER"
side = "BOTH"